# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
^Ibuild:
^Idocker:
^I# Use the same Docker base as the project
^I- image: python:3.7.3-stretch

^Iworking_directory: ~/repo

^Isteps:
^I- checkout

^I# Download and cache dependencies
^I- restore_cache:
^Ikeys:
^I- v1-dependencies-{{ checksum "requirements.txt" }}
^I# fallback to using the latest cache if no exact match is found
^I- v1-dependencies-

^I- run:
^Iname: install dependencies
^Icommand: |
^Ipython3 -m venv venv
^I. venv/bin/activate
^Imake install
^I# Install hadolint
^Iwget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 && chmod +x /bin/hadolint

^I- save_cache:
^Ipaths:
^I- ./venv
^Ikey: v1-dependencies-{{ checksum "requirements.txt" }}

^I# run lint!
^I- run:
^Iname: run lint
^Icommand: |
^I. venv/bin/activate
^Imake lint           
